In [1]:
import pandas as pd

In [5]:
chromo_df = pd.read_pickle('chromo_db_filtered.pkl')
overlap_df = pd.read_pickle('percent_overlap_df.pkl')

In [8]:
chromo_df.dropna(inplace=True)

In [9]:
chromo_df.loc[chromo_df['Solvent_iupac']=='chloroform']

,Chromophore,Solvent,Absorption max (nm),Emission max (nm),Solvent_iupac
0,CCCCCCCCCCCC#CC#CCCCCCCCCCN1C(=O)c2ccc3c4ccc5c...,ClC(Cl)Cl,526.0,535.0,chloroform
95,O=C1NC(=O)c2ccc(N3CCCCC3)c3cccc1c23,ClC(Cl)Cl,414.0,517.0,chloroform
96,O=C1NC(=O)c2ccc(N3CCOCC3)c3cccc1c23,ClC(Cl)Cl,394.0,504.0,chloroform
239,CCCCCCCCCCN1C(=O)c2cc(NCCCOCCO)c3c4c(cc(NCCCOC...,ClC(Cl)Cl,609.0,640.0,chloroform
240,CC(=O)OCCOCCN1C(=O)c2cc(NCCOCCO)c3c4c(cc(NCCOC...,ClC(Cl)Cl,610.0,640.0,chloroform
...,...,...,...,...,...
13405,c1cc2c3cscc3c3ccsc3c2s1,ClC(Cl)Cl,360.0,395.0,chloroform
13406,CCCCCCc1sc(CCCCCC)c2c3ccsc3c3sccc3c12,ClC(Cl)Cl,383.0,425.0,chloroform
13407,CCCCCCCCCCCCc1sc(CCCCCCCCCCCC)c2c3ccsc3c3sccc3c12,ClC(Cl)Cl,383.0,425.0,chloroform
13408,CCCCCCCCCCCCc1sc(CCCCCC)c2c3cc(CCCCCC)sc3c3sc(...,ClC(Cl)Cl,373.0,423.0,chloroform
13409,CCCCCCc1cc2c3cscc3c3cc(CCCCCC)sc3c2s1,ClC(Cl)Cl,393.0,442.0,chloroform

In [7]:
overlap_df.dropna()

,Chromo A,Chromo B,A: abs (nm),B: em (nm),Solvent,Percent Overlap
0,CCCCCCCCCCCC#CC#CCCCCCCCCCN1C(=O)c2ccc3c4ccc5c...,O=C1NC(=O)c2ccc(N3CCCCC3)c3cccc1c23,526.0,517.0,chloroform,6.525526e-01
1,CCCCCCCCCCCC#CC#CCCCCCCCCCN1C(=O)c2ccc3c4ccc5c...,O=C1NC(=O)c2ccc(N3CCOCC3)c3cccc1c23,526.0,504.0,chloroform,2.712789e-01
4,CCCCCCCCCCCC#CC#CCCCCCCCCCN1C(=O)c2ccc3c4ccc5c...,CCCCCCCCCCN1C(=O)c2cc(NCCCOCCO)c3c4c(cc(NCCCOC...,526.0,640.0,chloroform,1.189909e-08
5,CCCCCCCCCCCC#CC#CCCCCCCCCCN1C(=O)c2ccc3c4ccc5c...,CC(=O)OCCOCCN1C(=O)c2cc(NCCOCCO)c3c4c(cc(NCCOC...,526.0,640.0,chloroform,1.189909e-08
6,CCCCCCCCCCCC#CC#CCCCCCCCCCN1C(=O)c2ccc3c4ccc5c...,COCCOCCOCCN1C(=O)c2cc(NCCOCCO)c3c4c(cc(NCCOCCO...,526.0,640.0,chloroform,1.189909e-08
...,...,...,...,...,...,...
21198848,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccc4cccc5ccc2c3c45)c...,N#Cc1c(N2CCCCC2)cc(-c2ccccc2)c2c1Cc1ccccc1-2,344.0,449.0,oxolane,1.520510e-07
21198849,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccc4cccc5ccc2c3c45)c...,N#Cc1c(N2CCCCC2)cc(-c2cccc3ccccc23)c2c1Cc1cccc...,344.0,451.0,oxolane,8.676563e-08
21198850,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccc4cccc5ccc2c3c45)c...,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccccc3c2)c2c1Cc1cccc...,344.0,465.0,oxolane,1.469020e-09
21198851,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccc4cccc5ccc2c3c45)c...,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccc4cccc5ccc2c3c45)c...,344.0,481.0,oxolane,7.236394e-12
21198854,N#Cc1c(N2CCCCC2)cc(-c2ccc3ccc4cccc5ccc2c3c45)c...,N#Cc1c(N2CCCCC2)cc(-c2cccc3ccccc23)c2c1C(=O)c1...,344.0,460.0,oxolane,6.565336e-09